apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp1-clusterip-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp1-clusterip
    spec:
      containers:
       - name: webapp1-clusterip-pod
         image: katacoda/docker-http-server:latest
         ports:
          - containerPort:  80
